// <auto-generated />
using System;
using AspNet8Mvc_Tallybook.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspNet8Mvc_Tallybook.Migrations
{
    [DbContext(typeof(TallybookDBContext))]
    [Migration("20240509053128_initialdb")]
    partial class initialdb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspNet8Mvc_Tallybook.Models.ExpenseRecord", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("expenseType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("payDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("TallybookExpenseRecords");
                });

            modelBuilder.Entity("AspNet8Mvc_Tallybook.Models.ExpenseType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("expenseType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("TallybookExpenseTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
